# Generated by Django 3.0.4 on 2020-04-10 21:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Início')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Término')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departmentApi.Department', verbose_name='Área')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postApi.Post', verbose_name='Cargo')),
            ],
        ),
    ]
