# Generated by Django 3.0.4 on 2020-04-03 21:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('RG', 'Reunião Geral'), ('AS', 'Assembléia'), ('CF', 'Conferência'), ('OU', 'Outros')], max_length=3, null=True, verbose_name='Tipo do Evento')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Dia')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False, verbose_name='Presença')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Evento')),
            ],
        ),
    ]
