# Generated by Django 3.0.5 on 2020-04-08 19:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200408_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Reunião Geral', 'Reunião Geral'), ('Assembléia', 'Assembléia'), ('Conferência', 'Conferência'), ('Outros', 'Outros')], max_length=30, null=True, verbose_name='Tipo do Evento'),
        ),
    ]
