# Generated by Django 3.0.4 on 2020-04-03 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('REB', 'REB'), ('RA', 'Reunião de Área'), ('RT', 'Reunião de Time'), ('LR', 'Reunião de LR'), ('CN', 'Reunião de Corner')], max_length=3, null=True, verbose_name='Tipo da Reunião')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dia')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False, verbose_name='Presença')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='Reunião')),
            ],
        ),
    ]
