# Generated by Django 3.0.5 on 2020-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(blank=True, choices=[('REB', 'REB'), ('Reunião de Área', 'Reunião de Área'), ('Reunião de Time', 'Reunião de Time'), ('Reunião de LR', 'Reunião de LR'), ('Reunião de Corner', 'Reunião de Corner')], max_length=30, null=True, verbose_name='Tipo da Reunião'),
        ),
    ]
