# Generated by Django 3.0.4 on 2020-03-31 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentApi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postApi', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Background',
            new_name='Meeting',
        ),
        migrations.CreateModel(
            name='Meeting_Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False, verbose_name='Presença')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='Reunião')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
        ),
    ]
