# Generated by Django 3.0.4 on 2020-03-31 22:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0002_auto_20200331_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='post',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(blank=True, choices=[('REB', 'REB'), ('RA', 'Reunião de Área'), ('RT', 'Reunião de Time'), ('LR', 'Reunião de LR'), ('CN', 'Reunião de Corner')], max_length=3, null=True, verbose_name='Tipo da Reunião'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
