# Generated by Django 3.0.4 on 2020-03-18 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Dia')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora do check-in')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora do check-out')),
                ('duration', models.DurationField(blank=True, help_text='[HH:[MM:] format', null=True, verbose_name='Duração')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
        ),
    ]
