# Generated by Django 3.0.4 on 2020-04-08 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membershipCriteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstday_month', models.DateField(default=datetime.date.today, verbose_name='Primeiro dia do mês')),
                ('lastday_month', models.DateField(default=datetime.date.today, verbose_name='Último dia do mês')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeHour',
        ),
    ]
